10 generate cas file with bican hierarchy from anndata file
cellannotation/cas-tools pull request #36
Opened 2024-02-05 13:06 UTC by ubyndr

I've utilized cell IDs to infer the parent/child cluster hierarchy, and it appears that the outcome aligns with the co-annotation analysis results.

2024-02-05 13:06 UTC, ubyndr commented
<details>
  <summary>Click to show/hide the generated CAS without cell ids</summary>

```json
{
  "matrix_file_id": "TBA",
  "cellannotation_schema_version": "TBA",
  "cellannotation_timestamp": "TBA",
  "cellannotation_version": "TBA",
  "cellannotation_url": "TBA",
  "author_name": "TBA",
  "author_contact": "TBA",
  "orcid": "TBA",
  "annotations": [
    {
      "labelset": "cluster_id",
      "cell_label": 4,
      "cell_fullname": 4,
      "cell_set_accession": "6f3e2e7f20",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 5,
      "cell_fullname": 5,
      "cell_set_accession": "4e3939d257",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 6,
      "cell_fullname": 6,
      "cell_set_accession": "c508ff8d74",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 7,
      "cell_fullname": 7,
      "cell_set_accession": "8c00afa2bb",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 8,
      "cell_fullname": 8,
      "cell_set_accession": "770fef266f",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 9,
      "cell_fullname": 9,
      "cell_set_accession": "65d8b13fc6",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 10,
      "cell_fullname": 10,
      "cell_set_accession": "3fa2401d44",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 11,
      "cell_fullname": 11,
      "cell_set_accession": "973ee3d1fb",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 12,
      "cell_fullname": 12,
      "cell_set_accession": "ec2281a9d3",
      "cell_ontology_term_id": "CL:0000878",
      "cell_ontology_term": "central nervous system macrophage",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Microglia",
      "parent_cell_set_accession": "50c1cd0107"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 13,
      "cell_fullname": 13,
      "cell_set_accession": "09ed9b58fc",
      "cell_ontology_term_id": "CL:0000115",
      "cell_ontology_term": "endothelial cell",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Vascular",
      "parent_cell_set_accession": "e725e8ff77"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 14,
      "cell_fullname": 14,
      "cell_set_accession": "e2ddc23242",
      "cell_ontology_term_id": "CL:0000115",
      "cell_ontology_term": "endothelial cell",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "TBA",
      "parent_cell_set_name": "Vascular",
      "parent_cell_set_accession": "e725e8ff77"
    },
    {
      "labelset": "cluster_id",
      "cell_label": 15,
      "cell_fullname": 15,
      "cell_set_accession": "70b85acc4b",
      "cell_ontology_term_id": "CL:0000115",
      "cell_ontology_term": "endothelial cell",
      "cell_ids": [],
      "rationale": "TBA",
      "rationale_dois": "TBA",
      "marker_gene_evidence": "TBA",
      "synonyms": "TBA",
      "category_fullname": "TBA",
      "category_cell_ontology_exists": "TBA",
      "category_cell_ontology_term_id": "TBA",
      "category_cell_ontology_term": "T [...]

2024-02-05 13:07 UTC, ubyndr commented
<details>
  <summary>Click to show/hide the co-annotation analysis</summary>

| field_name1       | value1                                 | predicate       | field_name2       | value2                                 |
|-------------------|----------------------------------------|-----------------|-------------------|----------------------------------------|
| cell_type         | Bergmann glial cell                    | cluster_matches | cluster_id        | 51                                     |
| cell_type         | Bergmann glial cell                    | cluster_matches | supercluster_term | Bergmann glia                          |
| cell_type         | astrocyte                              | cluster_matches | supercluster_term | Astrocyte                              |
| cell_type         | central nervous system macrophage      | cluster_matches | supercluster_term | Microglia                              |
| cell_type         | choroid plexus epithelial cell         | cluster_matches | supercluster_term | Choroid plexus                         |
| cell_type         | endothelial cell                       | subcluster_of   | supercluster_term | Vascular                               |
| cell_type         | ependymal cell                         | cluster_matches | supercluster_term | Ependymal                              |
| cell_type         | fibroblast                             | cluster_matches | supercluster_term | Fibroblast                             |
| cell_type         | oligodendrocyte precursor cell         | cluster_matches | supercluster_term | Oligodendrocyte precursor              |
| cell_type         | pericyte                               | subcluster_of   | supercluster_term | Vascular                               |
| cell_type         | vascular associated smooth muscle cell | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 4                                      | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 4                                      | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 5                                      | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 5                                      | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 6                                      | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 6                                      | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 7                                      | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 7                                      | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 8                                      | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 8                                      | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 9                                      | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 9                                      | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 10                                     | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 10                                     | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 11                                     | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 11                                     | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 12                                     | subcluster_of   | supercluster_term | Microglia                              |
| cluster_id        | 12                                     | subcluster_of   | cell_type         | central nervous system macrophage      |
| cluster_id        | 13                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 13                                     | subcluster_of   | cell_type         | endothelial cell                       |
| cluster_id        | 14                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 14                                     | subcluster_of   | cell_type         | endothelial cell                       |
| cluster_id        | 15                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 15                                     | subcluster_of   | cell_type         | endothelial cell                       |
| cluster_id        | 16                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 16                                     | subcluster_of   | cell_type         | endothelial cell                       |
| cluster_id        | 17                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 17                                     | subcluster_of   | cell_type         | endothelial cell                       |
| cluster_id        | 18                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 18                                     | subcluster_of   | cell_type         | endothelial cell                       |
| cluster_id        | 19                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 19                                     | subcluster_of   | cell_type         | vascular associated smooth muscle cell |
| cluster_id        | 20                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 20                                     | subcluster_of   | cell_type         | vascular associated smooth muscle cell |
| cluster_id        | 21                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 21                                     | subcluster_of   | cell_type         | pericyte                               |
| cluster_id        | 22                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 22                                     | subcluster_of   | cell_type         | pericyte                               |
| cluster_id        | 23                                     | subcluster_of   | supercluster_term | Vascular                               |
| cluster_id        | 23                                     | subcluster_of   | cell_type         | pericyte                               |
| cluster_id        | 24                                     | subcluster_of   | supercluster_term | Fibroblast                             |
| cluster_id        | 24                                     | subcluster_of   | cell_type         | fibroblast                             |
| cluster_id        | 25                                     | subcluster_of   | supercluster_term | Fibroblast  [...]

2024-02-06 11:39 UTC, hkir-dev requested changes
- Can we remove `TBA` valued fields from the output?
- It will be a bit naive but can we generate `matrix_file_id ` from the AnnData file name
- Can we try to extract schema_version  from the `uns` ([schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#uns-dataset-metadata))
- Can you update `docs/cli.md`

2024-02-08 15:42 UTC, dosumis commented
Fixes #10

2024-02-12 09:40 UTC, hkir-dev approved these changes

2024-02-12 20:58 UTC, merged

2024-02-14 14:48 UTC, dosumis commented
@dosumis  to test