Spreadsheet to cas refactoring
cellannotation/cas-tools pull request #61
Opened 2024-03-20 00:08 UTC by ubyndr

Related with #34 

Implemented changes related with https://github.com/cellannotation/cas-tools/issues/34#issue-2110538012

### TODO
Validate schema compliance to ensure that the enhancement aligns with existing standards and expectations for dataset handling within our tools.

2024-03-20 11:18 UTC, hkir-dev requested changes

2024-03-20 11:18 UTC, hkir-dev commented on src/cas/spreadsheet_to_cas.py
>          labelset = row[LABELSET_COLUMN]
According to spec "columns names MUST match CAS annotation object key names". We don't need these mappings in the code, they should match by name. 

Before the loop we can read the headers in the spreadsheet and match with the fields in the CAS schema. Then we can then use this matching while extracting data from the rows. We can update the test data to match column names with the schema fields.

2024-03-20 11:18 UTC, hkir-dev commented on src/cas/spreadsheet_to_cas.py
>              "marker_gene_evidence": marker_gene_evidence,
can we use `|` separated list representation here.

2024-03-20 11:18 UTC, hkir-dev commented on src/cas/spreadsheet_to_cas.py
> +                meta_data[key] = value
`author_name`, `orcid` and `author_list` is not populated. Also we should get type of the field from schema and parse accordingly. Value of `author_list` should be list not string.

2024-03-20 11:38 UTC, ubyndr commented on src/test/spreadsheet_to_cas_test.py
> +            self.assertEqual(len(json_data), 4)
I've fixed this with my last [commit](https://github.com/cellannotation/cas-tools/pull/61/commits/730770483c8a378fd04246e861a4e30009df2696)

2024-03-21 12:48 UTC, hkir-dev approved these changes

2024-03-21 12:55 UTC, mfutey approved these changes

2024-03-21 14:38 UTC, merged